"""
Custom Prometheus Exporter for ML Metrics
Exposes:
- Request latency (P50, P95, P99)
- Throughput (requests/sec)
- Quality scores
- Error rates
"""

from prometheus_client import Counter, Histogram, Gauge, Info
import time

# ============================================
# CORE METRICS 
# ============================================

# 1. LATENCY METRICS
request_latency = Histogram(
    'ad_latency_seconds',
    'Latency of ad generation in seconds',
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0]
)

# 2. THROUGHPUT METRICS
total_requests = Counter(
    'ad_requests_total',
    'Total number of ad generation requests',
    ['status', 'endpoint']
)

successful_ads = Counter(
    'ad_throughput_total',
    'Total successfully generated ads'
)

# 3. QUALITY METRICS
quality_score = Histogram(
    'ad_quality_score',
    'Estimated quality score of generated ads (0-1)',
    buckets=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
)

# ============================================
# ADDITIONAL ML METRICS
# ============================================

# Model performance
model_load_time = Gauge(
    'model_load_time_seconds',
    'Time taken to load the model'
)

# Error tracking
error_count = Counter(
    'ad_errors_total',
    'Total number of errors',
    ['error_type']
)

# Token statistics
tokens_generated = Counter(
    'tokens_generated_total',
    'Total tokens generated by LLM'
)

# Active requests
active_requests = Gauge(
    'ad_active_requests',
    'Number of requests currently being processed'
)

# Cache metrics (if using caching)
cache_hits = Counter(
    'ad_cache_hits_total',
    'Number of cache hits'
)

cache_misses = Counter(
    'ad_cache_misses_total',
    'Number of cache misses'
)

# Response size
response_size = Histogram(
    'ad_response_size_bytes',
    'Size of ad creative responses in bytes',
    buckets=[50, 100, 200, 500, 1000, 2000]
)

# Model info
model_info = Info(
    'ad_model_info',
    'Information about the loaded model'
)

# ============================================
# HELPER FUNCTIONS
# ============================================

def track_request(status: str, endpoint: str = "/generate"):
    """Track a request with status"""
    total_requests.labels(status=status, endpoint=endpoint).inc()
    if status == "success":
        successful_ads.inc()

def track_latency(duration_seconds: float):
    """Track request latency"""
    request_latency.observe(duration_seconds)

def track_quality(score: float):
    """Track quality score"""
    quality_score.observe(score)

def track_error(error_type: str):
    """Track errors"""
    error_count.labels(error_type=error_type).inc()

def track_response_size(size_bytes: int):
    """Track response size"""
    response_size.observe(size_bytes)

def set_model_info(model_name: str, version: str, quantization: str):
    """Set model information"""
    model_info.info({
        'model_name': model_name,
        'version': version,
        'quantization': quantization
    })

def increment_active_requests():
    """Increment active requests counter"""
    active_requests.inc()

def decrement_active_requests():
    """Decrement active requests counter"""
    active_requests.dec()

# ============================================
# CONTEXT MANAGER FOR REQUEST TRACKING
# ============================================

class RequestTracker:
    """Context manager for tracking request metrics"""
    
    def __init__(self, endpoint: str = "/generate"):
        self.endpoint = endpoint
        self.start_time = None
        self.status = "error"  # Default to error, change on success
        
    def __enter__(self):
        self.start_time = time.time()
        increment_active_requests()
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        duration = time.time() - self.start_time
        decrement_active_requests()
        
        if exc_type is None:
            self.status = "success"
        else:
            error_type = exc_type.__name__ if exc_type else "unknown"
            track_error(error_type)
        
        track_request(self.status, self.endpoint)
        track_latency(duration)
        
        return False  # Don't suppress exceptions

# ============================================
# INITIALIZATION
# ============================================

def initialize_metrics():
    """Initialize default values for gauges"""
    active_requests.set(0)
    print("✅ Custom metrics exporter initialized")